import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { C, T } from '../lib/design'

const OPTIONS=[
 ['urgent_alerts','Alertas urgentes','Seguridad, incendios, salud y riesgos inmediatos.',true],
 ['event_reminders','Recordatorios de eventos','Avisos de eventos que sigues.',false],
 ['community_digest','Resumen del barrio','Una selección de actividad comunitaria.',false],
 ['marketplace','Mercado','Nuevas oportunidades, regalos y trueques.',false],
 ['commerce_promotions','Promociones locales','Ofertas de comercios cercanos.',false],
 ['general_push','Comunicaciones generales','Mensajes enviados por la administración.',false],
]
const DEFAULTS=Object.fromEntries(OPTIONS.map(([key,,,important])=>[key,important||key==='community_digest'||key==='event_reminders'||key==='general_push']))

export default function NotificationPreferences({ profileId,onNavigate }){
 const [prefs,setPrefs]=useState(DEFAULTS),[loading,setLoading]=useState(true),[saving,setSaving]=useState(''),[message,setMessage]=useState('')
 useEffect(()=>{if(!profileId)return;supabase.from('notification_preferences').select('*').eq('profile_id',profileId).maybeSingle().then(({data})=>{if(data)setPrefs(current=>({...current,...data}));setLoading(false)})},[profileId])
 const toggle=async key=>{if(OPTIONS.find(item=>item[0]===key)?.[3]&&prefs[key]){setMessage('Las alertas urgentes y los mensajes son esenciales. Puedes desactivarlos, pero podrías perder información importante.')}else setMessage('');const next=!prefs[key];setPrefs(current=>({...current,[key]:next}));setSaving(key);const{error}=await supabase.from('notification_preferences').upsert({profile_id:profileId,...prefs,[key]:next,updated_at:new Date().toISOString()});setSaving('');if(error){setPrefs(current=>({...current,[key]:!next}));setMessage('No pudimos guardar el cambio. Intenta nuevamente.')}}
 return <div style={s.wrap}><header style={s.header}><button style={s.back} onClick={()=>onNavigate?.('back')}>←</button><div><small style={s.kicker}>TU TRANQUILIDAD</small><h1 style={s.title}>Notificaciones</h1></div><span /></header><main style={s.main}><section style={s.hero}><span style={s.bell}>♢</span><div><strong>Tú decides qué merece interrumpirte</strong><p>Lo urgente llega al momento. El resto puede esperar.</p></div></section>{message&&<p style={s.message}>{message}</p>}<section style={s.list}>{loading?<p style={s.loading}>Cargando preferencias…</p>:OPTIONS.map(([key,title,copy,important])=><button key={key} style={s.row} onClick={()=>toggle(key)} disabled={saving===key}><span style={s.copy}><strong>{title}{important&&<em>Esencial</em>}</strong><small>{copy}</small></span><span style={{...s.switch,...(prefs[key]?s.switchOn:{})}}><i style={{...s.knob,...(prefs[key]?s.knobOn:{})}} /></span></button>)}</section><p style={s.footer}>Siempre podrás consultar todas tus notificaciones dentro de la aplicación, aunque desactives algunos avisos push.</p></main></div>
}
const s={wrap:{height:'100%',overflow:'auto',background:'#f6f9f7',fontFamily:T.font,color:C.texto},header:{minHeight:'var(--screen-header-height)',padding:'calc(env(safe-area-inset-top,0px) + 19px) 17px 14px',display:'grid',gridTemplateColumns:'38px 1fr 38px',alignItems:'center',textAlign:'center',background:'#fff',borderBottom:`1px solid ${C.borde}`},back:{width:38,height:38,border:`1px solid ${C.borde}`,borderRadius:'50%',background:'#fff',fontSize:20},kicker:{color:C.verde,fontSize:8,fontWeight:800},title:{margin:'2px 0 0',fontSize:17},main:{padding:'16px 16px 90px'},hero:{padding:16,display:'flex',gap:12,alignItems:'center',borderRadius:16,background:'#eaf8f2',border:'1px solid #ccebdc'},bell:{width:42,height:42,display:'grid',placeItems:'center',borderRadius:13,background:C.verde,color:'#fff',fontSize:25},copy:{flex:1,textAlign:'left',display:'grid',gap:4},list:{marginTop:14,border:`1px solid ${C.borde}`,borderRadius:16,overflow:'hidden',background:'#fff'},row:{width:'100%',minHeight:68,padding:'11px 13px',display:'flex',alignItems:'center',gap:10,border:0,borderBottom:`1px solid ${C.borde}`,background:'#fff'},copyStrong:{},switch:{width:42,height:24,padding:3,display:'block',flex:'0 0 auto',borderRadius:99,background:'#cfd8d2'},switchOn:{background:C.verde},knob:{display:'block',width:18,height:18,borderRadius:'50%',background:'#fff',boxShadow:'0 1px 3px rgba(0,0,0,.2)',transition:'transform .2s'},knobOn:{transform:'translateX(18px)'},message:{padding:10,borderRadius:10,background:'#fff8dc',color:'#80620a',fontSize:10,lineHeight:1.45},loading:{padding:20,textAlign:'center',color:C.textoSuave,fontSize:11},footer:{padding:'12px 5px',color:C.textoSuave,fontSize:9.5,lineHeight:1.5}}
