export const metadata = { title: 'Política de privacidad · El Barrio' }

const card = { padding: 22, marginBottom: 14, border: '1px solid #dce7df', borderRadius: 18, background: '#fff' }

export default function PrivacyPage() {
  return <main style={{ minHeight: '100vh', background: '#f5f8f6', color: '#18231d', fontFamily: 'Arial, sans-serif' }}>
    <header style={{ padding: '44px 22px 38px', background: '#1b9e75', color: '#fff' }}><div style={{ maxWidth: 780, margin: 'auto' }}><b style={{ fontSize: 12, letterSpacing: '.08em' }}>EL BARRIO</b><h1 style={{ margin: '8px 0 10px', fontSize: 42 }}>Política de privacidad</h1><p>Última actualización: 11 de agosto de 2026</p></div></header>
    <div style={{ maxWidth: 780, margin: 'auto', padding: '28px 22px 60px', lineHeight: 1.65 }}>
      <section style={card}><h2>1. Información que utilizamos</h2><p>El Barrio utiliza nombre, apellidos, correo electrónico, teléfono opcional y RUT para crear, proteger y verificar la cuenta. La dirección, comuna y ubicación GPS se usan para confirmar pertenencia territorial y ofrecer contenido cercano. El RUT, la dirección exacta y la ubicación precisa no se muestran públicamente a otros vecinos.</p></section>
      <section style={card}><h2>2. Contenido y actividad comunitaria</h2><p>Tratamos las publicaciones, fotografías, comentarios, opiniones, alertas, invitaciones, favoritos, acuerdos y mensajes privados necesarios para prestar las funciones solicitadas. El contenido que decides publicar puede ser visible para otros usuarios del barrio.</p></section>
      <section style={card}><h2>3. Finalidades</h2><ul><li>Crear, autenticar y proteger cuentas.</li><li>Verificar residencia y entregar contenido territorial.</li><li>Operar Mercado, Servicios, Comercios, Eventos, Alertas, mapas y mensajería.</li><li>Enviar notificaciones solicitadas.</li><li>Prevenir fraude, abuso y contenido prohibido.</li><li>Atender consultas y soporte.</li></ul></section>
      <section style={card}><h2>4. Permisos del dispositivo</h2><p>La cámara y galería se usan cuando eliges tomar o adjuntar imágenes. La ubicación se solicita para verificar el barrio y usar funciones cartográficas. Las notificaciones requieren autorización del dispositivo. Puedes administrar estos permisos desde Android.</p></section>
      <section style={card}><h2>5. Proveedores y seguridad</h2><p>El Barrio utiliza proveedores de infraestructura como Supabase para base de datos, autenticación y almacenamiento; Google para inicio de sesión; Firebase para notificaciones push; y proveedores de análisis automatizado cuando solicitas funciones de inteligencia artificial o corresponde moderar contenido público. No vendemos información personal. Los datos se transmiten mediante conexiones cifradas.</p></section>
      <section style={card}><h2>6. Moderación</h2><p>El contenido público puede analizarse automáticamente o revisarse administrativamente para detectar fraude, amenazas, acoso, actividad ilegal o exposición de información personal. Los mensajes privados no se envían al sistema de moderación de contenido público.</p></section>
      <section id="eliminacion" style={card}><h2>7. Eliminación y conservación</h2><p>Puedes eliminar tu cuenta desde <b>Perfil → Privacidad y seguridad → Eliminar mi cuenta</b>. También puedes solicitarla externamente. Al eliminarla se revoca el acceso y se anonimizan datos identificatorios. Algunas publicaciones, mensajes y registros mínimos de seguridad pueden conservarse anonimizados para preservar conversaciones, prevenir abuso o cumplir obligaciones aplicables.</p><a href="/eliminar-cuenta" style={{ display: 'inline-block', padding: '12px 16px', borderRadius: 10, background: '#126b4a', color: '#fff', fontWeight: 700 }}>Solicitar eliminación</a></section>
      <section style={card}><h2>8. Contacto</h2><p>Para consultas de privacidad escribe a <a href="mailto:contacto@elbarrio.lat">contacto@elbarrio.lat</a>.</p></section>
    </div>
  </main>
}
