import { useCallback, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase.js'
import { prepareImageUpload } from '../../../shared/imageUpload.js'

const EMPTY={title:'',description:'',image_url:'',starts_at:'',expires_at:'',is_active:true}
const inputDate=value=>{if(!value)return'';const d=new Date(value);if(Number.isNaN(d.getTime()))return'';return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}

export default function PromotionCatalog({commerce,onBack}){
  const [rows,setRows]=useState([]),[editing,setEditing]=useState(null),[editorOpen,setEditorOpen]=useState(false),[draft,setDraft]=useState(EMPTY),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('')
  const load=useCallback(async()=>{setLoading(true);const{data,error:loadError}=await supabase.from('commerce_promos').select('*').eq('commerce_id',commerce.id).order('created_at',{ascending:false});if(loadError)setError(loadError.message);setRows(data||[]);setLoading(false)},[commerce.id])
  useEffect(()=>{Promise.resolve().then(load)},[load])
  const open=item=>{setEditing(item||null);setDraft(item?{...item,starts_at:inputDate(item.starts_at),expires_at:inputDate(item.expires_at)}:EMPTY);setEditorOpen(true)}
  const upload=async event=>{const file=event.target.files?.[0];if(!file)return;setSaving(true);try{const prepared=await prepareImageUpload(file,`promos/${commerce.id}/${Date.now()}-${file.name}`);const{error:uploadError}=await supabase.storage.from('commerces').upload(prepared.path,prepared.file,{contentType:prepared.file.type});if(uploadError)throw uploadError;setDraft(d=>({...d,image_url:supabase.storage.from('commerces').getPublicUrl(prepared.path).data.publicUrl}))}catch(e){setError(e.message)}finally{setSaving(false)}}
  const save=async event=>{event.preventDefault();if(!draft.title.trim())return setError('El título es obligatorio.');setSaving(true);const payload={commerce_id:commerce.id,neighborhood_id:commerce.neighborhood_id,title:draft.title.trim(),description:draft.description.trim()||null,image_url:draft.image_url||null,starts_at:draft.starts_at?new Date(draft.starts_at).toISOString():null,expires_at:draft.expires_at?new Date(draft.expires_at).toISOString():null,is_active:draft.is_active};const request=editing?supabase.from('commerce_promos').update(payload).eq('id',editing.id):supabase.from('commerce_promos').insert(payload);const{error:saveError}=await request;setSaving(false);if(saveError)return setError(saveError.message);setEditing(null);setEditorOpen(false);setDraft(EMPTY);await load()}
  const remove=async item=>{if(!window.confirm(`¿Eliminar la promoción “${item.title}”?`))return;const{error:removeError}=await supabase.from('commerce_promos').delete().eq('id',item.id);if(removeError)return setError(removeError.message);await load()}
  return <div className="promo-catalog"><header className="subpage-header"><button className="subpage-back" onClick={onBack}>←</button><div><p className="eyebrow">Promociones</p><h1>{commerce.name}</h1><span>Crea, programa, pausa y elimina ofertas del comercio.</span></div><button className="button button-primary" onClick={()=>open(null)}>＋ Nueva promoción</button></header>{error&&<div className="admin-alert"><span>⚠️</span><p>{error}</p><button onClick={()=>setError('')}>×</button></div>}{editorOpen&&<form className="promo-editor" onSubmit={save}><label>Título<input value={draft.title} onChange={e=>setDraft(d=>({...d,title:e.target.value}))} required /></label><label className="wide">Descripción<textarea rows="4" value={draft.description||''} onChange={e=>setDraft(d=>({...d,description:e.target.value}))} /></label><label>Inicio<input type="datetime-local" value={draft.starts_at||''} onChange={e=>setDraft(d=>({...d,starts_at:e.target.value}))} /></label><label>Término<input type="datetime-local" value={draft.expires_at||''} onChange={e=>setDraft(d=>({...d,expires_at:e.target.value}))} /></label><label className="wide">Imagen<input type="file" accept="image/*" onChange={upload} />{draft.image_url&&<img src={draft.image_url} alt="" />}</label><label className="check"><input type="checkbox" checked={draft.is_active} onChange={e=>setDraft(d=>({...d,is_active:e.target.checked}))} /> Promoción activa</label><footer className="wide"><button type="button" onClick={()=>{setEditing(null);setEditorOpen(false);setDraft(EMPTY)}}>Cancelar</button><button type="submit" disabled={saving}>{saving?'Guardando…':'Guardar promoción'}</button></footer></form>} {loading?<div className="panel-loading">Cargando promociones…</div>:<section className="promo-grid">{rows.length===0?<div className="panel-empty"><strong>Sin promociones</strong></div>:rows.map(item=><article key={item.id}>{item.image_url&&<img src={item.image_url} alt="" />}<div><span>{item.is_active?'Activa':'Pausada'}</span><h3>{item.title}</h3><p>{item.description||'Sin descripción'}</p><small>{item.starts_at?new Date(item.starts_at).toLocaleDateString('es-CL'):'Inicio inmediato'} → {item.expires_at?new Date(item.expires_at).toLocaleDateString('es-CL'):'Sin término'}</small><footer><button onClick={()=>open(item)}>Editar</button><button onClick={()=>remove(item)}>Eliminar</button></footer></div></article>)}</section>}</div>
}
