import { useCallback, useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase.js'

const LABELS={comment:'Comentario',commerce_review:'Reseña de comercio',service_review:'Reseña de servicio'}
const dateLabel=value=>value?new Date(value).toLocaleString('es-CL',{dateStyle:'medium',timeStyle:'short'}):'Sin fecha'

export default function UserContentManager(){
  const [rows,setRows]=useState([]),[query,setQuery]=useState(''),[type,setType]=useState('all'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[removing,setRemoving]=useState('')
  const load=useCallback(async()=>{setLoading(true);setError('');const{data,error:loadError}=await supabase.rpc('admin_list_user_content');if(loadError)setError(loadError.message);setRows(data||[]);setLoading(false)},[])
  useEffect(()=>{Promise.resolve().then(load)},[load])
  const filtered=useMemo(()=>rows.filter(row=>(type==='all'||row.content_type===type)&&(!query.trim()||[row.parent_title,row.author_name,row.content].some(v=>String(v||'').toLowerCase().includes(query.trim().toLowerCase())))),[query,rows,type])
  const remove=async row=>{const reason=window.prompt(`Motivo para retirar este ${LABELS[row.content_type].toLowerCase()}:`)?.trim();if(!reason)return;if(!window.confirm('El contenido dejará de estar visible y se conservará una copia en la auditoría. ¿Continuar?'))return;setRemoving(row.content_id);const{error:removeError}=await supabase.rpc('admin_remove_user_content',{p_content_type:row.content_type,p_content_id:row.content_id,p_reason:reason});setRemoving('');if(removeError)return setError(removeError.message);setNotice('Contenido retirado y respaldado en auditoría');setTimeout(()=>setNotice(''),2500);await load()}
  return <div className="user-content-manager"><section className="page-heading"><div><p className="eyebrow">Moderación global</p><h1>Comentarios y reseñas</h1><p>Retira contenido abusivo sin alterar lo que escribió el usuario. Cada retiro conserva evidencia.</p></div></section>{error&&<div className="admin-alert"><span>⚠️</span><p>{error}</p><button onClick={()=>setError('')}>×</button></div>}{notice&&<div className="admin-toast">✓ {notice}</div>}<section className="user-content-tools"><label className="admin-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar contenido, autor o publicación…" /></label><select value={type} onChange={e=>setType(e.target.value)}><option value="all">Todo</option>{Object.entries(LABELS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></section>{loading?<div className="panel-loading">Cargando contenido…</div>:<section className="user-content-list">{filtered.length===0?<div className="panel-empty"><strong>Sin contenido en este filtro</strong></div>:filtered.map(row=><article key={`${row.content_type}-${row.content_id}`}><header><span>{LABELS[row.content_type]}</span><time>{dateLabel(row.created_at)}</time></header><h3>{row.parent_title||'Sin título'}</h3><small>Por {row.author_name||'Sin autor'}{row.rating?` · ${row.rating} estrellas`:''}</small><p>{row.content||'Sin texto'}</p><button type="button" disabled={removing===row.content_id} onClick={()=>remove(row)}>{removing===row.content_id?'Retirando…':'Retirar contenido'}</button></article>)}</section>}</div>
}
